# tests/lib/core.sh — DIVE-4891. Where the CORE CLI under test lives, and the
# `5dive` shim every carried harness drives.
#
# The council harnesses came from core (5dive-ai/5dive tests/council_*) and were
# written against ONE binary, `$ROOT/5dive`, that answered both `council` and
# everything council calls (gate-proof, task, agent). Here those are two programs:
# this repo's council/bin/council and a built core CLI. The shim written below is
# `$ROOT/5dive` again — `council` goes to the plugin, every other verb to core —
# so a harness reads exactly as it did in core and exercises the real seam: the
# plugin reaching core only through core's CLI.
#
# FIVEDIVE_CORE_DIR is a core checkout with `./build.sh` already run (CI clones
# 5dive-ai/5dive main into .core and builds it). Harnesses that source core's
# presentation libraries (src/lib/output.sh …) read them from there too.
FIVEDIVE_CORE_DIR="${FIVEDIVE_CORE_DIR:-$ROOT/.core}"
export FIVEDIVE_CORE_DIR
council_write_shim() {
  local core="$FIVEDIVE_CORE_DIR/5dive"
  [[ -x "$core" ]] || { echo "core CLI not built at $core — clone 5dive-ai/5dive into .core and run ./build.sh, or set FIVEDIVE_CORE_DIR" >&2; return 1; }
  cat > "$ROOT/5dive" <<SHIM
#!/usr/bin/env bash
# generated by tests/lib/core.sh — council -> this repo's plugin, the rest -> core
if [[ "\${1:-}" == "council" ]]; then shift; exec "$ROOT/council/bin/council" "\$@"; fi
exec "$core" "\$@"
SHIM
  chmod 0755 "$ROOT/5dive"
}
