#!/usr/bin/env bash
# `council` — the 5dive deliberation council, published as a plugin (DIVE-4891).
#
# THIS FILE IS GENERATED by council/src/gen.mjs from council/src/ (this prelude,
# cmd_council.template.sh and the three node modules). Edit the sources and
# re-run `node council/src/gen.mjs`; tests/council_plugin_unit.sh fails on drift.
#
# PROVENANCE. Everything below the prelude is core's `src/council/` at
# 5dive-ai/5dive fcd81d73 (DIVE-4869 phase 1), carried across verbatim apart from
# the divergences marked `PLUGIN DIVERGENCE` at their sites. Core keeps the
# constitution (the file, the one parser, the seal reader, the drift check and
# the tier-2 human-gate floor `task need` enforces); this plugin is the
# deliberation that AMENDS it — convene, ballots, seat motions, amendments, the
# founder veto, schedules and the lineage it seals them into.
#
# WHAT A PLUGIN CANNOT INHERIT. A plugin verb is an EXECUTABLE that core execs,
# not a sourced fragment, so nothing core defines is in scope: `fail`, `ok`,
# `warn`, the `E_*` codes, the node locator and the wizard's prompt helpers have
# to be re-established. That is what this prelude is. It re-establishes only
# PRESENTATION helpers. Every place the carried body reached into core's
# internals now goes through core's CLI instead:
#
#   core internal (in-process)            ->  what this plugin calls
#   cmd_gate_proof sign (the root seal)   ->  5dive gate-proof sign
#   db/sqlq on the task store             ->  5dive task show <id> --json
#   audit_log                             ->  5dive _audit_append (stdin NDJSON)
#   _task_agent_channel (principal)       ->  5dive agent telegram-access get <name> --json
#   _GATE_T2_FLOOR_RX (floor-diff)        ->  5dive constitution floor-rx (core >= the unwire release)
#
# ONE DATA SEAM IS LEFT, AND IT IS NAMED HERE. The founder-veto offer is a
# Telegram message with an inline VETO button, sent by the calling agent's bot.
# Core has no CLI verb that sends a message with a keyboard, so the offer reads
# the bot token from core's connector file (${CONNECTORS_DIR}/telegram-<agent>.env,
# 0640 root:claude) exactly as core did. If that layout changes the offer lapses —
# fail-safe by design (execution proceeds after the hold), never a wrong send.
#
# THE STORE IS UNCHANGED. Genesis, lineage, receipts, benches and schedules stay
# at ${STATE_DIR}/council/, the path core wrote them to, so a box that sealed a
# council before the move verifies the same chain after it. Core reads the newest
# `constitutionDigest` in that lineage as DATA to decide whether to trust
# constitution.yaml; this plugin is the only thing that writes multi-seat records.
# `set -euo pipefail` is applied by the entry trailer at the bottom, and only when
# this file is EXECUTED: the harnesses also source it for its function bodies, and
# errexit leaking into a sourcing shell would change what they measure.

STATE_DIR="${STATE_DIR:-/var/lib/5dive}"
CONNECTORS_DIR="${FIVEDIVE_CONNECTOR_DIR:-/etc/5dive/connectors}"
COUNCIL_SELF="${BASH_SOURCE[0]}"

# Error codes: values identical to core's src/lib/error_codes.sh, so a script that
# keys on `5dive council`'s exit status reads the same number it always did.
readonly E_OK=0
readonly E_GENERIC=1
readonly E_USAGE=2
readonly E_VALIDATION=3
readonly E_NOT_FOUND=4
readonly E_CONFLICT=5
readonly E_AUTH_REQUIRED=6
readonly E_NOT_INSTALLED=7
readonly E_NOT_RUNNING=8
readonly E_PERMISSION=10
readonly E_TIMEOUT=11

# Core strips a global `--json` out of argv and sets JSON_MODE before it
# dispatches; the carried body was written against that shape. The trailer at the
# bottom of this file does the same strip, so the body sees the argv it always
# saw. FIVEDIVE_JSON_MODE is honoured for a core that forwards the mode instead.
JSON_MODE="${FIVEDIVE_JSON_MODE:-0}"

_err_class_for() {
  case "$1" in
    2) echo usage ;; 3) echo validation ;; 4) echo not_found ;; 5) echo conflict ;;
    6) echo auth_required ;; 7) echo not_installed ;; 8) echo not_running ;;
    10) echo permission ;; 11) echo timeout ;; *) echo generic ;;
  esac
}

# fail <code> <message> — the same contract as core's: always exits with <code>;
# JSON mode also prints the {ok:false,error:{...}} envelope on stdout.
fail() {
  local code="$1"; shift
  if (( JSON_MODE )); then
    jq -cn --argjson c "$code" --arg cl "$(_err_class_for "$code")" --arg m "$*" \
      '{ok:false, error:{code:$c, class:$cl, message:$m}}'
  fi
  echo "error: $*" >&2
  exit "$code"
}
die()  { fail "$E_GENERIC" "$@"; }
warn() { echo "warn: $*" >&2; }
step() { echo "==> $*" >&2; }
# Core's backstop flag for "this exit was already explained"; the plugin has no
# EXIT-trap backstop, so marking is a no-op.
mark_reported() { :; }

# ok <prose-line> [jq-expr] [jq-args...] — core's contract verbatim.
ok() {
  local prose="${1:-}"; shift || true
  if (( JSON_MODE )); then
    local expr="${1:-}"
    [[ $# -gt 0 ]] && shift
    [[ -z "$expr" ]] && expr='{}'
    jq -cn "$@" "{ok:true, data: ($expr)}"
  else
    [[ -n "$prose" ]] && echo "OK — $prose"
  fi
  return 0
}

# The node locator, verbatim from core's src/lib/validation.sh: council is
# sudo-gated and root has no nvm node, so find one instead of dying.
_nvm_newest_node() {
  local home="$1" cand="" n
  while IFS= read -r n; do
    [[ -x "$n" ]] && cand="$n"
  done < <(printf '%s\n' "$home"/.nvm/versions/node/*/bin/node 2>/dev/null | sort -V)
  [[ -n "$cand" ]] || return 1
  printf '%s' "$cand"
}
ensure_node_on_path() {
  command -v node >/dev/null 2>&1 && return 0
  local d c cand="" home
  for d in /usr/local/bin /usr/bin /opt/homebrew/bin /snap/bin; do
    [[ -x "$d/node" ]] && { cand="$d"; break; }
  done
  if [[ -z "$cand" ]]; then
    for home in ${SUDO_USER:+"/home/$SUDO_USER"} /home/claude /root "${HOME:-/root}"; do
      c="$(_nvm_newest_node "$home")" || continue
      [[ -n "$c" ]] && { cand="$(dirname "$c")"; break; }
    done
  fi
  [[ -n "$cand" ]] || return 1
  PATH="$cand:$PATH"; export PATH
  return 0
}
require_node() {
  ensure_node_on_path && return 0
  fail "$E_NOT_INSTALLED" "${1:-this command} needs node on PATH and none was found (searched /usr/local/bin, /usr/bin, and ~/.nvm/versions/node for ${SUDO_USER:-root}/claude/root). Under \`sudo\`, root's PATH does not inherit nvm: sudo ln -s \"\$(command -v node)\" /usr/local/bin/node"
}

# ---- the core CLI seam -------------------------------------------------------
# The core CLI. COUNCIL_5DIVE_BIN is the carried body's own override (tests pin
# it to the binary under test); the default is whatever `5dive` is on PATH.
_council_core() { "${COUNCIL_5DIVE_BIN:-5dive}" "$@"; }

# The root seal. Core owns the gate-proof key; this plugin never reads it. As
# root we call the verb directly, otherwise through `sudo -n` — the same two
# routes the carried body always used for the non-root case.
cmd_gate_proof_sign_stdin() {
  if [[ "$(id -u)" -eq 0 ]]; then _council_core gate-proof sign
  else sudo -n "${COUNCIL_5DIVE_BIN:-5dive}" gate-proof sign; fi
}

# One task row as JSON (`.data.task`), or non-zero when there is no such row.
_council_task_json() {
  _council_core task show "$1" --json 2>/dev/null | jq -ce '.data.task // empty' 2>/dev/null
}

# audit_log <cmd> <result> <code> -- <args...> — one NDJSON row into core's
# tamper-evident log through its append-only primitive. Best-effort by contract,
# exactly like core's: a refused or missing append never fails the caller.
# COUNCIL_AUDIT_SINK (a file) redirects the row for a harness.
audit_log() {
  local cmd="$1" result="$2" code="$3"; shift 3
  [[ "${1:-}" == "--" ]] && shift
  local line
  line="$(jq -cn --arg ts "$(date -Iseconds)" --arg u "${SUDO_USER:-${USER:-root}}" \
    --arg c "$cmd" --arg r "$result" --argjson code "${code:-0}" \
    --args '{ts:$ts, user:$u, cmd:$c, result:$r, code:($code|tonumber? // 0), args:$ARGS.positional, via:"council-plugin"}' \
    -- "$@" 2>/dev/null)" || return 0
  if [[ -n "${COUNCIL_AUDIT_SINK:-}" ]]; then
    printf '%s\n' "$line" >> "$COUNCIL_AUDIT_SINK" 2>/dev/null || true
    return 0
  fi
  if [[ "$(id -u)" -eq 0 ]]; then
    printf '%s\n' "$line" | _council_core _audit_append >/dev/null 2>&1 || true
  else
    printf '%s\n' "$line" | sudo -n "${COUNCIL_5DIVE_BIN:-5dive}" _audit_append >/dev/null 2>&1 || true
  fi
  return 0
}

# The paired human of <agent>: allowFrom[0] of its Telegram access list, read
# through core's verb (which reads the 0600 file as that agent). Empty on a miss.
_council_agent_paired_human() {
  _council_core agent telegram-access get "$1" --json 2>/dev/null \
    | jq -r '(.data.access.allowFrom // [])[0] // empty' 2>/dev/null
}

# The calling agent — the seat whose bot carries a veto offer. Resolved from the
# REAL uid (SUDO_UID under sudo, else our own), never from $SUDO_USER or $USER,
# which the caller controls. Empty when the caller is not an agent-* account.
_council_caller_agent() {
  local uid="${SUDO_UID:-$(id -u)}" name
  name="$(getent passwd "$uid" 2>/dev/null | cut -d: -f1)"
  [[ "$name" == agent-* ]] && printf '%s' "${name#agent-}"
}

# The bot token for that agent — the ONE data seam named at the top of this file.
_council_agent_bot_token() {
  local name="$1" f
  [[ -n "$name" ]] || return 1
  f="${CONNECTORS_DIR}/telegram-${name}.env"
  [[ -r "$f" ]] || return 1
  sed -n 's/^TELEGRAM_BOT_TOKEN=//p' "$f" | head -1
}

# The single Telegram POST, with core's physical dry-run guard (DIVE-1500)
# carried verbatim: under FIVEDIVE_NOTIFY_DRYRUN a fixture can never reach a
# paired human, and a synthetic ok keeps downstream logic exercised.
_mirror_send() {
  local token="$1" chat="$2" thread="$3" text="$4" reply_markup="${5:-}"
  if [[ -n "${FIVEDIVE_NOTIFY_DRYRUN:-}" && "${FIVEDIVE_NOTIFY_DRYRUN}" != "0" ]]; then
    local dry_line
    dry_line=$(printf 'notify-dryrun chat=%s thread=%s markup=%s silent=%s text=%q' \
      "$chat" "${thread:-none}" "$([[ -n "$reply_markup" ]] && echo yes || echo no)" \
      "$([[ -n "${FIVEDIVE_NOTIFY_SILENT:-}" && "${FIVEDIVE_NOTIFY_SILENT}" != "0" ]] && echo yes || echo no)" "$text")
    if [[ -n "${FIVEDIVE_NOTIFY_DRYRUN_LOG:-}" ]]; then
      printf '%s\n' "$dry_line" >>"$FIVEDIVE_NOTIFY_DRYRUN_LOG" 2>/dev/null || true
    fi
    printf '%s\n' "$dry_line" >&2 || true
    printf '%s' '{"ok":true,"dry_run":true,"result":{"message_id":0}}'
    return 0
  fi
  local args=(--data-urlencode "chat_id=${chat}" --data-urlencode "text=${text}")
  [[ -n "$thread" ]] && args+=(--data-urlencode "message_thread_id=${thread}")
  [[ -n "$reply_markup" ]] && args+=(--data-urlencode "reply_markup=${reply_markup}")
  [[ -n "${FIVEDIVE_NOTIFY_SILENT:-}" && "${FIVEDIVE_NOTIFY_SILENT}" != "0" ]] \
    && args+=(--data-urlencode "disable_notification=true")
  curl -s --connect-timeout 5 --max-time 10 -X POST "https://api.telegram.org/bot${token}/sendMessage" "${args[@]}" 2>/dev/null
}

# ---- the `council init` wizard's prompt helpers (verbatim from core's cmd_init.sh) ----
__INIT_HELPERS__

# ==================== the carried body ====================
